name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Version from pubspec.yaml
        id: get_version
        working-directory: ./app
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "APP_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Build APK
        working-directory: ./app
        run: flutter build apk --release

      - name: Push Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f v${{ env.VERSION }}
          git push -f origin v${{ env.VERSION }}

      - name: Rename APK
        run: mv app/build/app/outputs/flutter-apk/app-release.apk app/build/app/outputs/flutter-apk/AutoRoomzio.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.APP_VERSION }}
          name: AutoRoomzio v${{ steps.get_version.outputs.APP_VERSION }}
          generate_release_notes: true
          files: app/build/app/outputs/flutter-apk/AutoRoomzio.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
